// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {param} from '../models';

export function CollectionDataAPI():Promise<any>;

export function ReadArchiveFileAPI(arg1:param.SelectDataParam):Promise<param.HWHArchiveDataListParam>;

export function ReadArchiveFileNameAPI():Promise<param.FileNameListParam>;

export function ReadExportFileAPI(arg1:param.SelectDataParam):Promise<param.ExportListParam>;

export function ReadFileNameAPI():Promise<param.FileNameListParam>;

export function ReadSystemSettingAPI():Promise<param.ModelFileParam>;

export function WriteExportFileAPI(arg1:param.SelectDataParam):Promise<param.ExportListParam>;

export function WriteSystemSettingAPI(arg1:param.ModelFileParam):Promise<param.ModelFileParam>;
