// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectionDataAPI() {
  return window['go']['end']['Backend']['CollectionDataAPI']();
}

export function ReadArchiveFileAPI(arg1) {
  return window['go']['end']['Backend']['ReadArchiveFileAPI'](arg1);
}

export function ReadArchiveFileNameAPI() {
  return window['go']['end']['Backend']['ReadArchiveFileNameAPI']();
}

export function ReadExportFileAPI(arg1) {
  return window['go']['end']['Backend']['ReadExportFileAPI'](arg1);
}

export function ReadFileNameAPI() {
  return window['go']['end']['Backend']['ReadFileNameAPI']();
}

export function ReadSystemSettingAPI() {
  return window['go']['end']['Backend']['ReadSystemSettingAPI']();
}

export function WriteExportFileAPI(arg1) {
  return window['go']['end']['Backend']['WriteExportFileAPI'](arg1);
}

export function WriteSystemSettingAPI(arg1) {
  return window['go']['end']['Backend']['WriteSystemSettingAPI'](arg1);
}
