// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function WindowFullscreen():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowQuit():Promise<void>;
